FROM openjdk:8-jdk-alpine
COPY ./itcast-service-mesh-movie-rating-1.0-SNAPSHOT.jar /movie/itcast-service-mesh-movie-rating-1.0-SNAPSHOT.jar
EXPOSE 18084

ENTRYPOINT [ "java","-jar","/movie/itcast-service-mesh-movie-rating-1.0-SNAPSHOT.jar" ]